### ISSUE TITLE
Reduce the decimal places on the kwh displays

### ISSUE THREAD

**Issue by gcoan** [Codegnosis/givtcp-battery-card#15]
Looks to be a useful additional custom card, thank you.  Easy to setup although I didn't need to add it as a custom repository.

Could you add the ability to reduce the decimal places on the kWh display please (or change the default).  Knowing its capacity and fullness is 9.5kWh is enough precision for me !
![image](https://github.com/Codegnosis/givtcp-battery-card/assets/142018870/4c874fc3-c58a-4f48-af15-ad6a11d2e98a)

**Comment by gcoan** [comment]
Further thought, rather than a hard kW or W display for the charging/discharging, make it intelligent (like the GivEnergy app) so it shows for example discharging at 269W or charging at 2.4kW
![image](https://github.com/Codegnosis/givtcp-battery-card/assets/142018870/ae417028-9ba9-435f-a57e-cf33225daab4)

**Comment by gcoan** [comment]
Sorry another thought, the batteries are currently charging at 2.4kW.  I've got a "time at 100%" that tells me when they will be fully charged all good.
But I don't understand why the "time left" is counting down.  The battery is charging so the time left should be increasing not decreasing, and how would the time left be calculated anyway when there isn't a discharge rate at the moment.
Maybe keep it constant and refresh say every x seconds reflecting the increasing soc ?

![image](https://github.com/Codegnosis/givtcp-battery-card/assets/142018870/d75b323d-ff3f-4710-bce9-16241d3debc8)

**Comment by Codegnosis** [comment]
Thanks for the feedback, much appreciated!

Regarding the intelligent unit display & decimal places - both are in the pipeline, and I'll hopefully have some time soon to implement.

Regarding the countdown timer - it's contextual, so if the battery is charging it's counting down the time until full. If it's discharging, it's counting down the time until it reaches the reserve %

**Comment by gcoan** [comment]
Thanks Paul. Obviously I didn't understand the countdown timer!

Look forward to seeing the next version.  This just popped up on my hacs dashboard.

Cheers Geoffrey

**Comment by gcoan** [comment]
Thanks Paul for the new features in the card, they work perfectly, just what I wanted
