### ISSUE TITLE
Add a depth of discharge setting 

### ISSUE THREAD

**Issue by ma9mwah** [Codegnosis/givtcp-battery-card#20]
I have a AIO unit which has a total capacity of 15.964 kWh but a usable capacity of 13.5 kWh. Currently the card lists the total and not the usable (which doesn't look to be listed in any sensor :( ). 

Would it be easy to have another setting that allows you to adjust the DOD to a set percentage (in my case 84.5%) to get the total numbers to align? I assumed the reported number of kWh left is just the Total * SOC%

**Comment by 1st-Ade** [comment]
Firstly, great card thank you.
I too have an AIO and would also appreciate if you could set the usable battery power level.

Thank you

**Comment by Codegnosis** [comment]
Thanks for the feedback, and glad you like the card!

You're right that the SOC values for the card come directly from the GivTCP `sensor.INVERTOR_SERIAL_soc_kwh` and `sensor.INVERTOR_SERIAL_soc` sensors. I'll have to investigate a little further to see how dependent these two values are on each other. On the surface, it seems the `soc` is just a percentage of `soc_kwh` based on the `sensor.INVERTOR_SERIAL_battery_capacity_kwh` value, so it may require some additional custom calculations on top of the GivTCP data to take DoD into account. I might be able to add a DoD config value to override and re-calculate these values if it's set.

**Comment by gcoan** [comment]
I have the same issue with my 5.2 battery that has an 80% dod but the full capacity gets reported.  TBH I wasn't all that bothered about the discrepancy

It's strange that the AIO reports the actual not the usable capacity as that's the newest GivEnergy battery. My 9.5 is 100% DoD that's achieved by having something like 12kW actual inside, but it's only ever reported as 9.5 available. You'd have thought the AIO would do the same

**Comment by 1st-Ade** [comment]
Cheers Paul

The SOC on the AIO seems to be part maths, part which craft with a bit of
devil's work in between 😂

For your info, the SOC that you battery card always matches that on my GE
app, which is not what I expected because your card appears to be a
percentage of the full 16kWh and I would have thought the GE app would have
been % of the usable 13.5kWh?  Or would it be the same anyhow because it's
a percentage?  Uuur, I haven't don the maths to answer that question yet.
Anyhow, thanks for the reply, love your app especially the estimation of
times to charge / discharge.

Regards

Adrian

**Comment by 1st-Ade** [comment]
Agreed.

I saw a post earlier today on FB where someone was asking about different
SOC being reported.

https://www.facebook.com/groups/489882062425810/permalink/907250877355591/

Greg Stewart who is very knowledgeable on GE said the one in the app is
usable and one on left is BMS value but that doesn't seem to tie up with
what it'll seeing.

It's a shame he didn't expand upon where the usable SOC is read from. I
guess it's calibration?

**Comment by ma9mwah** [comment]
I had a quick look into the code and I got it to work by adding a *0.85 on any line that has this._getBatteryCapacityKwhEntity.state or this._getSocKwhEntity.state

e.g. const t = parseFloat(this._getSocKwhEntity.state) * 1000 * 0.85

i tried adding an extra variable (defaulted to 100%) to the setting page to make it work and replace the hardcoded value above but couldnt get it to quite work

![Screenshot 2024-01-15 202931](https://github.com/Codegnosis/givtcp-battery-card/assets/21035345/9530b1b5-9d6f-4a51-b978-af89a7605ad8)

**Comment by Codegnosis** [comment]
Hi all - please check out `v0.2.0-beta.1` - https://github.com/Codegnosis/givtcp-battery-card/releases/tag/v0.2.0-beta.1

I might also need to adjust the reserve value, as this also affects the timers - do you know if the reserve is supposed to be calculated from the total battery capacity, or the DoD capacity?

**Comment by ma9mwah** [comment]
beta is working well :) but I believe (at least for the AIO) that the reserve should be based off the DOD Capacity.

![image](https://github.com/Codegnosis/givtcp-battery-card/assets/21035345/080fad34-3872-43fd-ae3e-dc757b633c84)

**Comment by gcoan** [comment]
The new beta appears good, being able to set the DoD on my 5.2 is really useful. At the moment the battery is being held at 100% reserve so I'll need to see it later for more feedback

As per the AIO, the reserve looks a bit weird, should be calculated as a % of usable not capacity? :
![image](https://github.com/Codegnosis/givtcp-battery-card/assets/142018870/380862d7-1f02-4081-9848-25ef9ba14bd9)

One other thing, I have "display number of decimal places set to 1" but this doesn't seem to be consistently applied.  Setting Dod back to 100% you can see it more clearly:
![image](https://github.com/Codegnosis/givtcp-battery-card/assets/142018870/d38393aa-be12-4fb5-bd0a-db030e5fa524)

**Comment by Codegnosis** [comment]
Thank you all so much for the feedback, very much appreciated! Please check out `v0.2.0-beta.2` - most of the above should be fixed

**Comment by ma9mwah** [comment]
Beta2 looks to have fixed the issues for me :) 

Could the DOD / Actual Cap line also be made an optional line as well like the bottom bar?

**Comment by Codegnosis** [comment]
> Beta2 looks to have fixed the issues for me :)
> 
> Could the DOD / Actual Cap line also be made an optional line as well like the bottom bar?

Thanks - I added the option. Please see `v0.2.0-beta.3`

**Comment by ma9mwah** [comment]
Perfect!
Looks to be working great on the AIO now 👍

**Comment by gcoan** [comment]
Thanks Paul for these fixes, I've tried beta 2 and 3 with my gen 1 hybrid and 5.2 battery.

Custom 80% dod works fine and the rounding is fixed now.

Showing the charge / discharge rates and % achieved of these isn't all that useful to me, it seems to discharge at 100.8% and discharge at 96% of the 2600w quoted. I can turn this off which is good.

Cheers Geoffrey

**Comment by 1st-Ade** [comment]
Thank you Paul

All now working fine on my AIO, really appreciate that.

Regards

Adrian

**Comment by gcoan** [comment]
I've just installed the official version and it's charging at kkw!
![IMG_6092](https://github.com/Codegnosis/givtcp-battery-card/assets/142018870/f537340b-0462-4103-b394-165745a520c8)

**Comment by gcoan** [comment]
And just noticed that the new switches are still marked as experimental?
![IMG_6093](https://github.com/Codegnosis/givtcp-battery-card/assets/142018870/5adaade1-dea8-40a6-904a-67f83d57487a)

**Comment by Codegnosis** [comment]
Thanks - an oversight when refactoring the code. Just released v0.2.1 with the fix.

**Comment by Codegnosis** [comment]
Please open a new issue with any new problems, because they may be overlooked if added to a closed issue :pray:

**Comment by gcoan** [comment]
New version corrects the kkw thanks Paul
