### ISSUE TITLE
Card doesn’t take account of kW unit of measure 

### ISSUE THREAD

**Issue by gcoan** [Codegnosis/givtcp-battery-card#21]
**Checklist:**

- [X] I updated to the latest version available
- [X ] I cleared the cache of my browser

**Release with the issue: v0.1.8

**Last working release (if known):**

iOS companion app and directly with Safari 

I recently changed the unit of measure for all my sensors to be consistent on using kW everywhere.

noticed that the card is indicating charging at 2W not 2KW - appears not to be taking account of the sensor’s unit of measurement 

![44E6D02F-6F57-45C3-ACEE-8EA695FF70A7](https://github.com/Codegnosis/givtcp-battery-card/assets/142018870/ee3fd94a-61f3-40eb-9582-81d8700df0c3)

**Description of problem:**

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

**Comment by gcoan** [comment]
It’s the givtcp_xxxx_battery_power sensor that’s being read but not taking account of the unit of measurement being W or kW.  The card assumes that the entity is always in watts

**Comment by Codegnosis** [comment]
Hi - unfortunately I haven't been able to reproduce this. With GivTCP v2.4.3, the `givtcp_INVERTORSERIAL_battery_power` always seems to return the power in Watts.

However, I'll keep investigating though to see if there is something in particular that triggers this scenario

**Comment by gcoan** [comment]
Thanks for looking into it, I had to change givtcp_xx_battery_sensor UOM  back to watts for the card to continue working.

Here's the card now:
![image](https://github.com/Codegnosis/givtcp-battery-card/assets/142018870/96f186c5-9a19-4726-9e29-476eee083643)

and the sensor:
![image](https://github.com/Codegnosis/givtcp-battery-card/assets/142018870/76c56e07-e9fb-46e7-8ae3-c2499da1ecfa)

If I change the UOM on the sensor to kW:
![image](https://github.com/Codegnosis/givtcp-battery-card/assets/142018870/bf325eae-c293-4860-8b51-f5ebab48ff7f)

the card still thinks its reading the battery power in watts, not the kW its been set to:
![image](https://github.com/Codegnosis/givtcp-battery-card/assets/142018870/10dd642f-20cd-4851-8462-e4d583f6e591)

Unfortunately I am on GivTCP 2.4.1 as 2.4.3 crashes with with "can't find serial number". Weirdly it does this on one of my two inverters not the other, but it stops working almost as soon after I upgrade.
I have raised an issue on GivTCP over this bug as I'd like to upgrade, but still no response from brikkat

**Comment by Codegnosis** [comment]
Thanks for the info - where is the UOM info changed/condifured from W to kW in HA? Perhaps I can have a play and see what I can do. If the w/kw value is saved in the `givtcp_INVERTORSERIAL_battery_power` attributes, it should be relatively trivial to modify the code and support this for you

**Comment by gcoan** [comment]
If you go into integrations/entities, search for the entity _battery_power

Click it (the right one, there are a few similarly named) to you see the details

Click the cog to edit the sensor

Then UOM is third entry on the screen,  can change it between kW and W

Click Update to save

I assumed it would be straight forward to add this, thanks

**Comment by gcoan** [comment]
Thanks for the fix, it appears to work perfectly, I can change the battery power between kW and W and the charge rate always shows as 2.4kW
